version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
    rust: "1.91"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
